name: Update images
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * 0' # Weekly on Sundays at 03:00

env:
  IMAGE_NAME: common/plone-base

jobs:
  build-push-notify:
    runs-on: gha-runners
    strategy:
      matrix:
        include:
          - tag: 4.3.20-ubuntu
            context: 4.3.20/ubuntu/py2
            dockerfile: 4.3.20/ubuntu/py2/Dockerfile
          - tag: 6.0.9
            context: 6.0/6.0.9/ubuntu
            dockerfile: 6.0/6.0.9/ubuntu/Dockerfile
          - tag: 6.0.13
            context: 6.0/6.0.13/ubuntu
            dockerfile: 6.0/6.0.13/ubuntu/Dockerfile
          - tag: 6.0.14
            context: 6.0/6.0.14/ubuntu
            dockerfile: 6.0/6.0.14/ubuntu/Dockerfile
          - tag: 6.1.0
            context: 6.1/6.1.0/ubuntu
            dockerfile: 6.1/6.1.0/ubuntu/Dockerfile
          - tag: 6.1.1
            context: 6.1/6.1.1/ubuntu
            dockerfile: 6.1/6.1.1/ubuntu/Dockerfile
          - tag: 6.1.2
            context: 6.1/6.1.2/ubuntu
            dockerfile: 6.1/6.1.2/ubuntu/Dockerfile
    steps:
      - name: Build, push and notify for ${{ matrix.tag }}
        uses: IMIO/gha/build-push-notify@v3.2
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAGS: |
            ${{ secrets.HARBOR_URL }}/${{ env.IMAGE_NAME }}:${{ matrix.tag }}
          REGISTRY_URL: ${{ secrets.HARBOR_URL }}
          REGISTRY_USERNAME: ${{ secrets.COMMON_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.COMMON_HARBOR_PASSWORD }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.COMMON_MATTERMOST_WEBHOOK_URL }}
          CONTEXT: ${{ matrix.context }}
          DOCKERFILE: ${{ matrix.dockerfile }}