name: Update images
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * 0' # Weekly on Sundays at 03:00
jobs:
  debian_4_3_20_py2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: 4.3.20-debian
        uses: docker/build-push-action@v2.5.0
        with:
          context: 4.3.20/debian/py2/
          tags: imiobe/plone-base:4.3.20-debian
          pull: true
          push: true
  ubuntu_4_3_20_py2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: 4.3.20-ubuntu
        uses: docker/build-push-action@v2.5.0
        with:
          context: 4.3.20/ubuntu/py2/
          tags: imiobe/plone-base:4.3.20-ubuntu
          pull: true
          push: true
  alpine_5_2_6_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: 5.2.5-alpine
        uses: docker/build-push-action@v2.5.0
        with:
          context: 5.2/5.2.6/alpine/py3/
          tags: imiobe/plone-base:5.2.6-alpine
          pull: true
          push: true
