name: Update images
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * 0' # Weekly on Sundays at 03:00
jobs:
  ubuntu_4_3_20_py2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: 4.3.20-ubuntu
        uses: docker/build-push-action@v2.5.0
        with:
          context: 4.3.20/ubuntu/py2/
          tags: imiobe/plone-base:4.3.20-ubuntu
          platforms: linux/amd64
          pull: true
          push: true
  alpine_5_2_13_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v2.5.0
        with:
          context: 5.2/5.2.13/alpine/py3/
          tags: imiobe/plone-base:5.2.13-alpine
          platforms: linux/amd64
          pull: true
          push: true
  ubuntu_6_0_8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v2.5.0
        with:
          context: 6.0/6.0.8/ubuntu
          tags: imiobe/plone-base:6.0.8-ubuntu
          platforms: linux/amd64
          pull: true
          push: true
  ubuntu_6_0_4_py3:
    runs-on:
      group: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.COMMON_HARBOR_USERNAME }}
          password: ${{ secrets.COMMON_HARBOR_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v2.5.0
        with:
          context: 6.0/6.0.4/ubuntu
          tags: ${{ secrets.HARBOR_URL }}/common/plone-base:6.0.4-ubuntu
          platforms: linux/amd64
          pull: true
          push: true
  ubuntu_6_0_9_py3:
    runs-on:
      group: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.COMMON_HARBOR_USERNAME }}
          password: ${{ secrets.COMMON_HARBOR_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v2.5.0
        with:
          context: 6.0/6.0.9/ubuntu
          tags: ${{ secrets.HARBOR_URL }}/common/plone-base:6.0.9-ubuntu
          platforms: linux/amd64
          pull: true
          push: true